[package]
name = "redpact-desktop"
version = "0.5.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dunce = "1.0.5"
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
serde_json = "1"
url = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
